### ISSUE TITLE
Tiers descriptions missing

### ISSUE THREAD

**Issue by andrewpalmeruk** [rcpch/api-management-platform#6]
Both on the logged-out and logged-in experiences of https://dev.rcpch.ac.uk/ there is talk of three tiers, but with no description as to what the differences are, nor how much each costs.

Actually, the page loads and shows some tier information (see screenshot) but then quickly redraws itself to hide this information.

![image](https://user-images.githubusercontent.com/65177313/100144246-6a626880-2e8e-11eb-9138-3d9b56b6468a.png)

**Comment by pacharanero** [comment]
I think this may be an issue with the API management platform itself. ie a bug. You're right @andrewpalmeruk it appears to draw the tiers then they disappear. The platform itself seems rather glitchy and erratic (much like Azure itself) 

We may be able to fix it, but it's possible we'll actually need to self-host the Azure APIM platform in order to get that level of granular, code-level control over the HTML templates.

Would @atheneheaven or @andrewpalmeruk be interested in looking into this a bit further? Azure is to some extent a familiar environment for you.

**Comment by pacharanero** [comment]
#1
