### ISSUE TITLE
Blue background breaks accessibility rules

### ISSUE THREAD

**Issue by andrewpalmeruk** [rcpch/api-management-platform#8]
The on-brand blue backgrounds make the blue POST text difficult to read:

![image](https://user-images.githubusercontent.com/65177313/100144547-d6dd6780-2e8e-11eb-8425-31790e91ddd2.png)

**Comment by pacharanero** [comment]
This is unfortunately also caused by Azure's API management platform.

You can only have one set of styling for a 'Menu' - although the image shows three I had to set all of them the same in order to get the top right 'RCPCH Style' menu to look right.
![image](https://user-images.githubusercontent.com/2348385/108516566-49a78480-72be-11eb-911c-77d6da3d9e96.png)

Unfortunately the choices we make for this RCPCH menu
![image](https://user-images.githubusercontent.com/2348385/108516329-0220f880-72be-11eb-9918-c4b607d4ca8a.png)

Get applied to this menu in the API selector
![image](https://user-images.githubusercontent.com/2348385/108516354-0b11ca00-72be-11eb-99ab-038e14b545c2.png)

I fully agree it looks terrible and is virtually unusable.

I am actually very happy for someone else to have a look at this and a play around and see if they can get it any better. It may be that with some clever arrangement of the various options we can get what we want.

It is also possible to Self Host the API Management Platform inside Azure. The managed product uses JSON data for all this styling and there is no way to change templates or styling in code. The self-hosted product still integrates with Azure in the same way but gives us more control. https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal

Alternatively we could switch to another API Management platform entirely.... But that would I think add complexity.

**Comment by kirsten-olson** [comment]
Hi @pacharanero  and @andrewpalmeruk 

Thanks for this update. I think I follow that the same styling (blue background/white text) gets applied to all menus. And, I'm assuming that we can't, or shouldn't, change the text colour of the actions POST and GET?

I'm not sure how complex it is at this stage to self host the API platform within Azure for more design control. 

I'd be happy to look at this, perhaps with Andrew/others in our IS team? I'm definitely no expert on CSS, though!

I wonder whether we should consider a different styling for the menus, still using our brand colours, but perhaps light grey colour background and dark blue or strong blue colour text - which would ensure the POST and GET are visible. I could check in with @Jo-Ball next week. 

Thanks!
Kirsten

**Comment by pacharanero** [comment]
Thanks @kirsten-olson 

Self hosting might fix some of this as we could over-ride any undesirable appearances with CSS. I will have a look at the tutorial and maybe try setting it up to test (while not over-riding the managed version we're using for now)

Some careful wysiwyg editing on the actual dev portal might yield a good enough result to get it looking better though..... @andrewpalmeruk can give you the permissions you need

**Comment by kirsten-olson** [comment]
Hi @pacharanero

@Jo-Ball and I spoke about this. We suggest changing the styling of the menu to:
- Background-color: Light grey - the lightest grey in our brand is #D9D9D9, but we can go for a lighter grey if needed. We use #F0F0F0 on many of our blocks in our main site, eg to display related content links 
- Font-color: Dark blue #0D0D58 or Black #000000  

We think that will work pretty well for both the header and API selector menu, and ensure the 'POST' and 'GET' text is accessible.

Is it easy for you/someone to update this styling? Noted a longer term option might be to set up a new portal. 

Thanks!
Kirsten
